# Generated by Django 5.1.6 on 2025-03-04 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeklifTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('konu', models.CharField(max_length=200, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Teklif Talebi',
                'verbose_name_plural': 'Teklif Talepleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
