# Generated by Django 5.1.6 on 2025-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(default='Hoş Geldiniz', max_length=100, verbose_name='Karşılama Metni')),
                ('title', models.CharField(default='Profesyonel Çatı', max_length=200, verbose_name='Ana Başlık')),
                ('rotating_words', models.TextField(help_text='Her kelimeyi yeni bir satıra yazın', verbose_name='Dönen Kelimeler')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('background_image', models.ImageField(upload_to='hero/', verbose_name='Arka Plan Görseli')),
                ('button_text', models.CharField(default='Teklif Al', max_length=50, verbose_name='Buton Metni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Hero',
                'verbose_name_plural': 'Ana Sayfa Hero',
            },
        ),
    ]
