# Generated by Django 5.1.6 on 2025-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('resim', models.ImageField(upload_to='medya/', verbose_name='Resim')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
            ],
            options={
                'verbose_name': 'Medya',
                'verbose_name_plural': 'Medya Galerisi',
                'ordering': ['-yukleme_tarihi'],
            },
        ),
    ]
