# Generated by Django 5.1.6 on 2025-03-20 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processed', 'İşlendi'), ('answered', 'Yanıtlandı')], default='pending', max_length=20, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='medya',
            options={'ordering': ['-yukleme_tarihi'], 'verbose_name': 'Medya', 'verbose_name_plural': 'Medya'},
        ),
        migrations.AlterField(
            model_name='medya',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medya',
            name='resim',
            field=models.ImageField(upload_to='medya/'),
        ),
        migrations.AlterField(
            model_name='medya',
            name='yukleme_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
