# Generated by Django 5.1.6 on 2025-03-20 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_alter_medya_options_alter_medya_baslik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(upload_to='site/', verbose_name='Site Logo')),
                ('menu_anasayfa', models.CharField(default='Ana Sayfa', max_length=50, verbose_name='Ana Sayfa Menü')),
                ('menu_cati', models.CharField(default='Çatı Sistemleri', max_length=50, verbose_name='Çatı Sistemleri Menü')),
                ('menu_izolasyon', models.CharField(default='İzolasyon', max_length=50, verbose_name='İzolasyon Menü')),
                ('menu_bakim', models.CharField(default='Bakım & Onarım', max_length=50, verbose_name='Bakım & Onarım Menü')),
                ('menu_projeler', models.CharField(default='Projeler', max_length=50, verbose_name='Projeler Menü')),
                ('menu_referanslar', models.CharField(default='Referanslar', max_length=50, verbose_name='Referanslar Menü')),
                ('menu_iletisim', models.CharField(default='İletişim', max_length=50, verbose_name='İletişim Menü')),
                ('footer_logo', models.ImageField(upload_to='site/', verbose_name='Footer Logo')),
                ('footer_telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('footer_email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('footer_adres', models.TextField(verbose_name='Adres')),
                ('footer_copyright', models.CharField(max_length=200, verbose_name='Copyright Metni')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil Fotoğrafı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
