# Generated by Django 5.1.6 on 2025-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pagecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='content_description',
            field=models.TextField(default='Uzman ekibimiz ve kaliteli malzemelerimizle çatı sistemleriniz için en iyi çözümleri sunuyoruz.', verbose_name='İçerik Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='content_title',
            field=models.CharField(default='Profesyonel Çatı Çözümleri', max_length=200, verbose_name='İçerik Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_desc_1',
            field=models.TextField(default='Her türlü çatı onarım ve bakım hizmetleri', verbose_name='Özellik Açıklama 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_desc_2',
            field=models.TextField(default='Su ve ısı yalıtımı çözümleri', verbose_name='Özellik Açıklama 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_desc_3',
            field=models.TextField(default='Modern çatı sistemleri kurulumu', verbose_name='Özellik Açıklama 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_desc_4',
            field=models.TextField(default='Periyodik bakım ve kontrol', verbose_name='Özellik Açıklama 4'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_link_1',
            field=models.URLField(default='#', verbose_name='Özellik Link 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_link_2',
            field=models.URLField(default='#', verbose_name='Özellik Link 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_link_3',
            field=models.URLField(default='#', verbose_name='Özellik Link 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_link_4',
            field=models.URLField(default='#', verbose_name='Özellik Link 4'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_title_1',
            field=models.CharField(default='Çatı Onarımı', max_length=100, verbose_name='Özellik Başlık 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_title_2',
            field=models.CharField(default='Çatı İzolasyonu', max_length=100, verbose_name='Özellik Başlık 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_title_3',
            field=models.CharField(default='Çatı Sistemleri', max_length=100, verbose_name='Özellik Başlık 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_title_4',
            field=models.CharField(default='Bakım Hizmeti', max_length=100, verbose_name='Özellik Başlık 4'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='services_description',
            field=models.TextField(default='Modern çatı sistemleri, izolasyon çözümleri ve bakım hizmetleri ile yapılarınızı koruyoruz.', verbose_name='Hizmetler Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='services_title',
            field=models.CharField(default='Size Özel Çözümler', max_length=200, verbose_name='Hizmetler Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='why_choose_description',
            field=models.TextField(default='Profesyonel ekibimiz ve kaliteli malzemelerimizle çatı sistemleriniz için en iyi çözümleri sunuyoruz.', verbose_name='Neden Biz Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='why_choose_title',
            field=models.CharField(default='Kaliteli Hizmet, Uygun Fiyat', max_length=200, verbose_name='Neden Biz Başlık'),
        ),
    ]
