# Generated by Django 5.1.6 on 2025-03-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_pagecontent_siteayarlari_content_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='İçerik Resmi'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Özellik Resim 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Özellik Resim 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Özellik Resim 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Özellik Resim 4'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='why_choose_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Neden Biz Resmi'),
        ),
    ]
