# Generated by Django 5.1.6 on 2025-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteayarlari_content_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medya',
            name='kategori',
            field=models.CharField(choices=[('feature', 'Özellik Resmi'), ('content', 'İçerik Resmi'), ('why_choose', 'Neden Biz Resmi'), ('other', 'Diğer')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='medya',
            name='kullanım_alani',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medya',
            name='yukleme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
