# Generated by Django 5.1.6 on 2025-03-27 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medya_kategori_medya_kullanım_alani_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medya',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='medya',
            name='kullanım_alani',
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='detail_text_1',
            field=models.CharField(default='Profesyonel ekip ve ekipman', max_length=200, verbose_name='Detay Metin 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='detail_text_2',
            field=models.CharField(default='Kaliteli malzeme', max_length=200, verbose_name='Detay Metin 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='detail_text_3',
            field=models.CharField(default='Uzun ömürlü çözümler', max_length=200, verbose_name='Detay Metin 3'),
        ),
        migrations.AlterField(
            model_name='medya',
            name='yukleme_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
