# Generated by Django 5.1.6 on 2025-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_medya_kategori_remove_medya_kullanım_alani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='why_choose_subtitle',
            field=models.CharField(default='NEDEN BİZ?', max_length=100, verbose_name='Neden Biz Alt Başlık'),
        ),
    ]
