# Generated by Django 5.1.6 on 2025-03-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteayarlari_why_choose_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='services_subtitle',
            field=models.CharField(default='HİZMETLERİMİZ', max_length=100, verbose_name='Hizmetler Alt Başlık'),
        ),
    ]
