# Generated by Django 5.1.6 on 2025-03-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_siteayarlari_modern_roof_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='card2_description',
            field=models.TextField(default='Profesyonel izolasyon çözümleri', verbose_name='İkinci Kart Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='card2_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='İkinci Kart Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='card2_link',
            field=models.URLField(default='#', verbose_name='İkinci Kart Link'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='card2_title',
            field=models.CharField(default='Çatı İzolasyonu', max_length=200, verbose_name='İkinci Kart Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='card3_description',
            field=models.TextField(default='Düzenli bakım ve onarım hizmetleri', verbose_name='Üçüncü Kart Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='card3_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Üçüncü Kart Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='card3_link',
            field=models.URLField(default='#', verbose_name='Üçüncü Kart Link'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='card3_title',
            field=models.CharField(default='Çatı Bakımı', max_length=200, verbose_name='Üçüncü Kart Başlık'),
        ),
    ]
