# Generated by Django 5.1.6 on 2025-03-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_siteayarlari_card2_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='modern_roof_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Modern Çatı Resim'),
        ),
    ]
