# Generated by Django 5.1.6 on 2025-03-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_siteayarlari_modern_roof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='project_background',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Proje Arka Plan Resmi'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project_description',
            field=models.TextField(default='Başarıyla tamamladığımız projelerimizden örnekleri inceleyin. Modern tasarımlar ve profesyonel uygulamalar ile fark yaratıyoruz.', verbose_name='Proje Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project_subtitle',
            field=models.CharField(default='PROJELER', max_length=100, verbose_name='Proje Alt Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project_title',
            field=models.CharField(default='Tamamlanan Projelerimiz', max_length=200, verbose_name='Proje Başlık'),
        ),
    ]
