# Generated by Django 5.1.6 on 2025-03-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_siteayarlari_project_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='project_background_position',
            field=models.CharField(default='center center', help_text='Örnek: center center, top center, bottom center, center left, center right', max_length=50, verbose_name='Proje Arka Plan Konumu'),
        ),
    ]
