# Generated by Django 5.1.6 on 2025-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_siteayarlari_project_background_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='services_background',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Hizmetler Arka Plan'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='services_background_position',
            field=models.CharField(default='center center', max_length=50, verbose_name='Hizmetler Arka Plan Konumu'),
        ),
    ]
