# Generated by Django 5.1.6 on 2025-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_siteayarlari_services_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post1_description',
            field=models.TextField(default='Blog post 1 açıklaması burada yer alacak.', verbose_name='Blog Post 1 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post1_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Blog Post 1 Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post1_link',
            field=models.URLField(default='#', verbose_name='Blog Post 1 Link'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post1_title',
            field=models.CharField(default='Blog Post 1 Başlık', max_length=200, verbose_name='Blog Post 1 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post2_description',
            field=models.TextField(default='Blog post 2 açıklaması burada yer alacak.', verbose_name='Blog Post 2 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post2_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Blog Post 2 Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post2_link',
            field=models.URLField(default='#', verbose_name='Blog Post 2 Link'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post2_title',
            field=models.CharField(default='Blog Post 2 Başlık', max_length=200, verbose_name='Blog Post 2 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post3_description',
            field=models.TextField(default='Blog post 3 açıklaması burada yer alacak.', verbose_name='Blog Post 3 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post3_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Blog Post 3 Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post3_link',
            field=models.URLField(default='#', verbose_name='Blog Post 3 Link'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_post3_title',
            field=models.CharField(default='Blog Post 3 Başlık', max_length=200, verbose_name='Blog Post 3 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_section_description',
            field=models.TextField(default='En son haberler, güncellemeler ve blog yazılarımız', verbose_name='Blog Bölüm Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='blog_section_title',
            field=models.CharField(default='Son Haberler', max_length=200, verbose_name='Blog Bölüm Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_address',
            field=models.TextField(default='2601 Beaumont Ave Liberty, Texas', verbose_name='İletişim Adres'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_description',
            field=models.TextField(default='Bizimle iletişime geçmek için aşağıdaki formu doldurun.', verbose_name='İletişim Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_email',
            field=models.EmailField(default='info@ustcati.com', max_length=254, verbose_name='İletişim E-posta'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_phone',
            field=models.CharField(default='+1-(903) 482-5172', max_length=20, verbose_name='İletişim Telefon'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_title',
            field=models.CharField(default='İletişime Geçin', max_length=200, verbose_name='İletişim Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='why_choose_link',
            field=models.URLField(default='#', verbose_name='Neden Biz Link'),
        ),
    ]
