# Generated by Django 5.1.6 on 2025-04-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_siteayarlari_blog_post1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='cta_description',
            field=models.TextField(default='Ücretsiz keşif ve fiyat teklifi için hemen bizimle iletişime geçin.', verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='cta_title',
            field=models.CharField(default='Çatınız İçin Profesyonel Çözümler', max_length=200, verbose_name='CTA Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature1_description',
            field=models.TextField(default='En zorlu hava koşullarına karşı tam koruma sağlayan çatı sistemleri.', verbose_name='Özellik 1 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature1_title',
            field=models.CharField(default='Maksimum Koruma', max_length=200, verbose_name='Özellik 1 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature2_description',
            field=models.TextField(default='Isı yalıtımı ile enerji tasarrufu sağlayan akıllı çözümler.', verbose_name='Özellik 2 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature2_title',
            field=models.CharField(default='Enerji Verimliliği', max_length=200, verbose_name='Özellik 2 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature3_description',
            field=models.TextField(default='Uzman ekibimiz ile hatasız ve hızlı montaj hizmeti.', verbose_name='Özellik 3 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='feature3_title',
            field=models.CharField(default='Profesyonel Montaj', max_length=200, verbose_name='Özellik 3 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='features_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Özellikler Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='features_title',
            field=models.CharField(default='Neden Çatı Sistemlerimizi Tercih Etmelisiniz?', max_length=200, verbose_name='Özellikler Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_step1_description',
            field=models.TextField(default='Ücretsiz keşif hizmeti ile ihtiyaçlarınızı belirleyelim.', verbose_name='Süreç Adım 1 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_step1_title',
            field=models.CharField(default='Keşif', max_length=200, verbose_name='Süreç Adım 1 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_step2_description',
            field=models.TextField(default='Size özel çatı sistemi planlaması yapalım.', verbose_name='Süreç Adım 2 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_step2_title',
            field=models.CharField(default='Planlama', max_length=200, verbose_name='Süreç Adım 2 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_step3_description',
            field=models.TextField(default='Profesyonel ekibimiz ile montajı gerçekleştirelim.', verbose_name='Süreç Adım 3 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_step3_title',
            field=models.CharField(default='Uygulama', max_length=200, verbose_name='Süreç Adım 3 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_step4_description',
            field=models.TextField(default='Son kontroller ile kalite güvencesi sağlayalım.', verbose_name='Süreç Adım 4 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_step4_title',
            field=models.CharField(default='Kontrol', max_length=200, verbose_name='Süreç Adım 4 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='process_title',
            field=models.CharField(default='Çatı Sistemi Kurulum Süreci', max_length=200, verbose_name='Süreç Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_systems_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Çatı Sistemleri Hero Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_systems_solutions_title',
            field=models.CharField(default='Çatı Sistemleri Çözümlerimiz', max_length=200, verbose_name='Çatı Sistemleri Çözümler Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_systems_subtitle',
            field=models.TextField(default='Yenilikçi teknolojiler ve uzman ekibimizle çatınızı geleceğe hazırlıyoruz', verbose_name='Çatı Sistemleri Alt Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_systems_title',
            field=models.CharField(default='Modern Çatı Sistemleri', max_length=200, verbose_name='Çatı Sistemleri Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type1_description',
            field=models.TextField(default='Geleneksel ve modern kiremit çatı sistemleri ile binanızın estetiğini ve dayanıklılığını artırın.', verbose_name='Kiremit Çatı Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type1_feature1',
            field=models.CharField(default='Uzun Ömürlü Dayanıklılık', max_length=200, verbose_name='Kiremit Çatı Özellik 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type1_feature2',
            field=models.CharField(default='Estetik Görünüm', max_length=200, verbose_name='Kiremit Çatı Özellik 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type1_feature3',
            field=models.CharField(default='Doğal Havalandırma', max_length=200, verbose_name='Kiremit Çatı Özellik 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type1_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Kiremit Çatı Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type1_title',
            field=models.CharField(default='Kiremit Çatı Sistemleri', max_length=200, verbose_name='Kiremit Çatı Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type2_description',
            field=models.TextField(default='Hafif, dayanıklı ve modern metal çatı sistemleri ile yapınızı güvence altına alın.', verbose_name='Metal Çatı Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type2_feature1',
            field=models.CharField(default='Hafif Yapı', max_length=200, verbose_name='Metal Çatı Özellik 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type2_feature2',
            field=models.CharField(default='Hızlı Montaj', max_length=200, verbose_name='Metal Çatı Özellik 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type2_feature3',
            field=models.CharField(default='Minimum Bakım', max_length=200, verbose_name='Metal Çatı Özellik 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type2_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Metal Çatı Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type2_title',
            field=models.CharField(default='Metal Çatı Sistemleri', max_length=200, verbose_name='Metal Çatı Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type3_description',
            field=models.TextField(default='Modern ve estetik shingle çatı sistemleri ile yapınıza değer katın.', verbose_name='Shingle Çatı Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type3_feature1',
            field=models.CharField(default='Çeşitli Renk Seçenekleri', max_length=200, verbose_name='Shingle Çatı Özellik 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type3_feature2',
            field=models.CharField(default='Kolay Uygulama', max_length=200, verbose_name='Shingle Çatı Özellik 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type3_feature3',
            field=models.CharField(default='Ekonomik Çözüm', max_length=200, verbose_name='Shingle Çatı Özellik 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type3_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Shingle Çatı Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='roof_type3_title',
            field=models.CharField(default='Shingle Çatı Sistemleri', max_length=200, verbose_name='Shingle Çatı Başlık'),
        ),
    ]
