# Generated by Django 5.1.6 on 2025-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_siteayarlari_cta_description_siteayarlari_cta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_form_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_form_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_hero_subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='contact_hero_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='map_embed_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='social_media_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='working_hours_saturday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='working_hours_sunday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='working_hours_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='working_hours_weekday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='contact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='contact_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='contact_phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
