# Generated by Django 5.1.6 on 2025-04-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_siteayarlari_contact_form_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_insulation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project1_warranty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_insulation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project2_warranty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_insulation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='project3_warranty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='projects_active',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='projects_completed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='projects_customers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='projects_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='projects_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='projects_hero_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='projects_hero_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
