# Generated by Django 5.1.6 on 2025-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_siteayarlari_project1_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='brand1_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='brand2_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='brand3_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='brand4_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate1_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate1_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate1_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate2_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate2_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate3_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate3_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate3_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate4_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate4_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='certificate4_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='references_cta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='references_cta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='references_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='references_hero_subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='references_hero_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial1_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial1_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial1_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial2_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial2_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial2_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial3_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial3_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='testimonial3_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
