# Generated by Django 5.1.6 on 2025-04-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_siteayarlari_brand1_image_siteayarlari_brand2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='service1_description',
            field=models.TextField(blank=True, null=True, verbose_name='Hizmet 1 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service1_feature1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 1 Özellik 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service1_feature2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 1 Özellik 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service1_feature3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 1 Özellik 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service1_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 1 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service2_description',
            field=models.TextField(blank=True, null=True, verbose_name='Hizmet 2 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service2_feature1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 2 Özellik 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service2_feature2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 2 Özellik 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service2_feature3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 2 Özellik 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service2_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 2 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service3_description',
            field=models.TextField(blank=True, null=True, verbose_name='Hizmet 3 Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service3_feature1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 3 Özellik 1'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service3_feature2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 3 Özellik 2'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service3_feature3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 3 Özellik 3'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='service3_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet 3 Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='services_cta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Hizmetler CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='services_cta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmetler CTA Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='services_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='medya/', verbose_name='Hizmetler Hero Resim'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='services_hero_subtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Hizmetler Hero Alt Başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='services_hero_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmetler Hero Başlık'),
        ),
    ]
