# Generated by Django 5.1.6 on 2025-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_siteayarlari_service1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('description', models.TextField(verbose_name='Proje Açıklaması')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Proje Resmi')),
                ('category', models.CharField(choices=[('residential', 'Konut'), ('commercial', 'Ticari'), ('industrial', 'Endüstriyel')], max_length=50, verbose_name='Kategori')),
                ('location', models.CharField(max_length=200, verbose_name='Konum')),
                ('area', models.CharField(max_length=50, verbose_name='Alan')),
                ('duration', models.CharField(max_length=50, verbose_name='Süre')),
                ('material', models.CharField(max_length=100, verbose_name='Malzeme')),
                ('insulation', models.CharField(max_length=100, verbose_name='İzolasyon')),
                ('warranty', models.CharField(max_length=50, verbose_name='Garanti')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Proje Detayları')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
