# Generated by Django 5.1.6 on 2025-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Ana Sayfa Hero', 'verbose_name_plural': 'Ana Sayfa Hero'},
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
    ]
