# Generated by Django 5.1.6 on 2025-04-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_herosection_options_herosection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Haritalar Linki'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cep Telefonu'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Arka Plan Görseli'),
        ),
    ]
