# Generated by Django 5.1.6 on 2025-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_siteayarlari_google_maps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='facebook_aktif',
            field=models.BooleanField(default=True, verbose_name='Facebook Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='instagram_aktif',
            field=models.BooleanField(default=True, verbose_name='Instagram Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='linkedin_aktif',
            field=models.BooleanField(default=True, verbose_name='LinkedIn Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='twitter_aktif',
            field=models.BooleanField(default=True, verbose_name='Twitter Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='youtube_aktif',
            field=models.BooleanField(default=True, verbose_name='YouTube Aktif'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
