# Generated by Django 5.1.6 on 2025-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_siteayarlari_facebook_aktif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='footer_adres_aktif',
            field=models.BooleanField(default=True, verbose_name='Adres Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='footer_email_aktif',
            field=models.BooleanField(default=True, verbose_name='E-posta Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='footer_telefon_aktif',
            field=models.BooleanField(default=True, verbose_name='Telefon Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='google_maps_url_aktif',
            field=models.BooleanField(default=True, verbose_name='Google Haritalar Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='mobile_phone_aktif',
            field=models.BooleanField(default=True, verbose_name='Cep Telefonu Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='whatsapp_aktif',
            field=models.BooleanField(default=True, verbose_name='WhatsApp Aktif'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='footer_adres',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='footer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='footer_telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Google Haritalar Linki'),
        ),
    ]
