# Generated by Django 5.1.6 on 2025-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_siteayarlari_footer_adres_aktif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='footer_description',
            field=models.TextField(blank=True, null=True, verbose_name='Footer Açıklama'),
        ),
    ]
