# Generated by Django 5.1.6 on 2025-04-22 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('description', models.TextField(verbose_name='Proje Açıklaması')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Proje Görseli')),
                ('completion_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tamamlanma Tarihi')),
                ('location', models.CharField(max_length=200, verbose_name='Proje Konumu')),
                ('client', models.CharField(max_length=200, verbose_name='Müşteri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
