# Generated by Django 5.1.6 on 2025-04-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_customer_service_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Tamamlandı'), ('ongoing', 'Devam Ediyor'), ('planned', 'Planlandı'), ('pending', 'Beklemede')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
