# Generated by Django 5.1.6 on 2025-04-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
