# Generated by Django 5.1.6 on 2025-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_offer_status_remove_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('menu_anasayfa', models.CharField(default='Ana Sayfa', max_length=50)),
                ('menu_cati', models.CharField(default='Çatı Sistemleri', max_length=50)),
                ('menu_projeler', models.CharField(default='Projeler', max_length=50)),
                ('menu_referanslar', models.CharField(default='Referanslar', max_length=50)),
                ('menu_iletisim', models.CharField(default='İletişim', max_length=50)),
                ('footer_telefon', models.CharField(max_length=20)),
                ('footer_email', models.EmailField(max_length=254)),
                ('footer_adres', models.TextField()),
                ('footer_copyright', models.CharField(max_length=200)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
