# Generated by Django 5.1.6 on 2025-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_siteayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='menu_hizmetler',
            field=models.CharField(default='Hizmetler', max_length=50),
        ),
    ]
